// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommentBox: typeof import('./src/components/comment-box/src/comment-box.vue')['default']
    CommentItem: typeof import('./src/components/comment-item/src/comment-item.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    MomentItem: typeof import('./src/components/moment-item/src/moment-item.vue')['default']
    MomentUser: typeof import('./src/components/moment-user/src/moment-user.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/nav-header.vue')['default']
    PostArea: typeof import('./src/components/post-area/src/post-area.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadAvatar: typeof import('./src/components/upload-avatar/src/upload-avatar.vue')['default']
    UploadImages: typeof import('./src/components/upload-images/src/upload-images.vue')['default']
    UserInfo: typeof import('./src/components/user-info/src/user-info.vue')['default']
  }
}

export {}
